### ISSUE TITLE
File rearrangement

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [distributethe6ix/70DaysOfServiceMesh#1]
The current file name makes the files shuffled according to the number precedence
![Example file arrangement now](https://i.imgur.com/FkaoiJf.png)
We can rename the first 9 files to something like `01-xyx` , `02-xyz` so it follows the number precendance

**Comment by shivarm** [comment]
hey @kaiwalyakoparkar i want to work on this issue

**Comment by distributethe6ix** [comment]
@kaiwalyakoparkar @shivam-sharma7 feel free to file a PR with your suggestions! And THANK YOU for helping out!

**Comment by shivam-sharma7** [comment]
review/ @distributethe6ix

**Comment by distributethe6ix** [comment]
File names updated, looks clean now.
