### ISSUE TITLE
Attach files with Topics in README.md

### ISSUE THREAD

**Issue by shivarm** [distributethe6ix/70DaysOfServiceMesh#11]
Hi Marino,

I want to attach all files in readme.md which can be helpful for people who want to directly jump on the topics that he really want.

# Demo
![Screenshot (35)](https://user-images.githubusercontent.com/91419219/216806279-96c0d54b-36a1-408f-9b77-ef9c1dc85d71.png)

**Comment by shivarm** [comment]
@distributethe6ix/  can you assign me? if you would like to do something like that.

**Comment by distributethe6ix** [comment]
Go for it :)!!

I was thinking about doing this but haven't had any time but appreciate you taking initiative with this one!

**Comment by shivarm** [comment]
> Go for it :)!!
> 
> I was thinking about doing this but haven't had any time but appreciate you taking initiative with this one!

Thanks
