### ISSUE TITLE
delete `README.md` file into 70DaysOfServiceMesh folder

### ISSUE THREAD

**Issue by shivarm** [distributethe6ix/70DaysOfServiceMesh#17]
hi,

@distributethe6ix should we delete `README.md` into 70DaysOfServiceMesh folder

**Comment by distributethe6ix** [comment]
I'm not sure what you mean @shivam-sharma7 can you explain a bit more?

**Comment by shivarm** [comment]
why we have same [Readme.md](https://github.com/distributethe6ix/70DaysOfServiceMesh/blob/main/70DaysExercises/README.md) file inside the 70DaysOfServiceMesh folder
