### ISSUE TITLE
Badges aren't aligned properly.

### ISSUE THREAD

**Issue by distributethe6ix** [distributethe6ix/70DaysOfServiceMesh#28]
![Screenshot 2023-03-16 at 5 25 43 AM](https://user-images.githubusercontent.com/45947861/225573230-e1a12f7f-10da-48c1-a79b-c82602ca389d.png)

See attached image above.

**Comment by shivarm** [comment]
## fixed now

![image](https://user-images.githubusercontent.com/91419219/225578962-510a3f90-692c-461d-9ac8-fbcc4faf2403.png)
