### ISSUE TITLE
03-Comparing Different Service Meshes.md Exercises Missing

### ISSUE THREAD

**Issue by shivarm** [distributethe6ix/70DaysOfServiceMesh#4]
- 03-Comparing Different Service Meshes.md Exercises Missing in [70DaysOfServiceMesh](https://github.com/distributethe6ix/70DaysOfServiceMesh/tree/main/70DaysExercises)

![Screenshot (29)](https://user-images.githubusercontent.com/91419219/211182396-9dfcc141-8ad7-4d8b-88d9-7bd6f3acd70b.png)

**Comment by Vinujaaa** [comment]
Hey, 
It is present in the folder as [3-Comparing Different Service Meshes.md](https://github.com/distributethe6ix/70DaysOfServiceMesh/blob/main/70DaysExercises/3-Comparing%20Different%20Service%20Meshes.md) 

Raising a PR to rename it.

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/113903063/211211383-3e47ff1f-220d-44a0-a506-f0004b408f07.png">
